// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AuthorizeInvoiceData, AuthorizeInvoiceErrors, AuthorizeInvoiceResponses, CreateInvoiceData, CreateInvoiceErrors, CreateInvoiceResponses, GetApiInfo2Data, GetApiInfo2Responses, GetApiInfoData, GetApiInfoResponses, GetDetailedHealth2Data, GetDetailedHealth2Errors, GetDetailedHealth2Responses, GetDetailedHealthData, GetDetailedHealthErrors, GetDetailedHealthResponses, GetInvoiceData, GetInvoiceErrors, GetInvoicePdfData, GetInvoicePdfErrors, GetInvoicePdfResponses, GetInvoiceResponses, GetInvoiceXmlData, GetInvoiceXmlErrors, GetInvoiceXmlResponses, ListCertificatesData, ListCertificatesResponses, ListInvoicesData, ListInvoicesResponses, SendInvoiceData, SendInvoiceErrors, SendInvoiceResponses, UploadCertificateData, UploadCertificateErrors, UploadCertificateResponses, VoidInvoiceData, VoidInvoiceErrors } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Basic health check
 */
export const getApiInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiInfoData, ThrowOnError>) => (options?.client ?? client).get<GetApiInfoResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Detailed health check
 *
 * Comprehensive health check including database and storage status
 */
export const getDetailedHealth = <ThrowOnError extends boolean = false>(options?: Options<GetDetailedHealthData, ThrowOnError>) => (options?.client ?? client).get<GetDetailedHealthResponses, GetDetailedHealthErrors, ThrowOnError>({ url: '/health/health', ...options });

/**
 * Basic health check
 */
export const getApiInfo2 = <ThrowOnError extends boolean = false>(options?: Options<GetApiInfo2Data, ThrowOnError>) => (options?.client ?? client).get<GetApiInfo2Responses, unknown, ThrowOnError>({ url: '/v1/health', ...options });

/**
 * Detailed health check
 *
 * Comprehensive health check including database and storage status
 */
export const getDetailedHealth2 = <ThrowOnError extends boolean = false>(options?: Options<GetDetailedHealth2Data, ThrowOnError>) => (options?.client ?? client).get<GetDetailedHealth2Responses, GetDetailedHealth2Errors, ThrowOnError>({ url: '/v1/health/health', ...options });

/**
 * List invoices
 *
 * Retrieve a paginated list of invoices for the organization
 */
export const listInvoices = <ThrowOnError extends boolean = false>(options?: Options<ListInvoicesData, ThrowOnError>) => (options?.client ?? client).get<ListInvoicesResponses, unknown, ThrowOnError>({ url: '/v1/invoices', ...options });

/**
 * Create invoice
 *
 * Create a new invoice in draft status
 */
export const createInvoice = <ThrowOnError extends boolean = false>(options?: Options<CreateInvoiceData, ThrowOnError>) => (options?.client ?? client).post<CreateInvoiceResponses, CreateInvoiceErrors, ThrowOnError>({
    url: '/v1/invoices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Void invoice
 *
 * Void/cancel an invoice (not yet implemented)
 */
export const voidInvoice = <ThrowOnError extends boolean = false>(options: Options<VoidInvoiceData, ThrowOnError>) => (options.client ?? client).delete<unknown, VoidInvoiceErrors, ThrowOnError>({ url: '/v1/invoices/{id}', ...options });

/**
 * Get invoice by ID
 *
 * Retrieve a single invoice with all its items
 */
export const getInvoice = <ThrowOnError extends boolean = false>(options: Options<GetInvoiceData, ThrowOnError>) => (options.client ?? client).get<GetInvoiceResponses, GetInvoiceErrors, ThrowOnError>({ url: '/v1/invoices/{id}', ...options });

/**
 * Send invoice to SRI
 *
 * Sign and send the invoice to SRI for processing
 */
export const sendInvoice = <ThrowOnError extends boolean = false>(options: Options<SendInvoiceData, ThrowOnError>) => (options.client ?? client).post<SendInvoiceResponses, SendInvoiceErrors, ThrowOnError>({ url: '/v1/invoices/{id}/send', ...options });

/**
 * Authorize invoice
 *
 * Check authorization status with SRI after sending
 */
export const authorizeInvoice = <ThrowOnError extends boolean = false>(options: Options<AuthorizeInvoiceData, ThrowOnError>) => (options.client ?? client).post<AuthorizeInvoiceResponses, AuthorizeInvoiceErrors, ThrowOnError>({ url: '/v1/invoices/{id}/authorize', ...options });

/**
 * Download RIDE PDF
 *
 * Generate and download the RIDE PDF for an invoice
 */
export const getInvoicePdf = <ThrowOnError extends boolean = false>(options: Options<GetInvoicePdfData, ThrowOnError>) => (options.client ?? client).get<GetInvoicePdfResponses, GetInvoicePdfErrors, ThrowOnError>({ url: '/v1/invoices/{id}/pdf', ...options });

/**
 * Download signed XML
 *
 * Download the signed XML document for an invoice
 */
export const getInvoiceXml = <ThrowOnError extends boolean = false>(options: Options<GetInvoiceXmlData, ThrowOnError>) => (options.client ?? client).get<GetInvoiceXmlResponses, GetInvoiceXmlErrors, ThrowOnError>({ url: '/v1/invoices/{id}/xml', ...options });

/**
 * Upload P12 certificate
 *
 * Upload a P12 electronic signature certificate for signing invoices
 */
export const uploadCertificate = <ThrowOnError extends boolean = false>(options?: Options<UploadCertificateData, ThrowOnError>) => (options?.client ?? client).post<UploadCertificateResponses, UploadCertificateErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/v1/certificates/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * List certificates
 *
 * List all certificates for the organization
 */
export const listCertificates = <ThrowOnError extends boolean = false>(options?: Options<ListCertificatesData, ThrowOnError>) => (options?.client ?? client).get<ListCertificatesResponses, unknown, ThrowOnError>({ url: '/v1/certificates', ...options });
