// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.ecuapi.com' | 'http://localhost:8787' | (string & {});
};

export type HealthResponse = {
    status: 'healthy' | 'degraded';
    name?: string;
    version?: string;
    environment?: string;
    docs?: string;
    checks?: {
        api: string;
        database: string;
        storage: string;
    };
    timestamp?: string;
};

export type InvoiceListResponse = {
    data: Array<Invoice>;
    meta: Meta;
};

export type Invoice = {
    id: string;
    organizationId: string;
    status: string;
    type: string;
    subtotal: number;
    taxAmount: number;
    totalAmount: number;
    accessKey: string;
    recipientName: string;
    recipientId: string;
    recipientPhone: string;
    createdAt: string;
    updatedAt: string;
};

export type Meta = {
    requestId: string;
    timestamp: string;
    page?: number;
    perPage?: number;
    total?: number;
    totalPages?: number;
};

export type CreateInvoiceResponse = {
    data: {
        id: string;
        subtotal: number;
        taxAmount: number;
        total: number;
        status: string;
    };
    meta: Meta;
};

export type Error = {
    error: {
        code: string;
        message: string;
    };
};

export type CreateInvoiceRequest = {
    customer: Customer;
    items: Array<InvoiceItem>;
    /**
     * 01 = Sin sistema financiero
     */
    paymentMethod?: string;
    notes?: string;
};

export type Customer = {
    /**
     * RUC, Cédula, or Passport
     */
    id: string;
    idType: 'ruc' | 'cedula' | 'passport' | 'final';
    name: string;
    email?: string;
    address?: string;
    phone?: string;
};

export type InvoiceItem = {
    code?: string;
    description: string;
    quantity: number;
    /**
     * Price in cents
     */
    unitPrice: number;
    discount?: number;
    /**
     * SRI tax code
     */
    taxCode: '0' | '2' | '3' | '4' | '5' | '6' | '7' | '8';
};

export type InvoiceDetailResponse = {
    data: Invoice & {
        items: Array<unknown>;
    };
    meta: Meta;
};

export type SendInvoiceResponse = {
    data: {
        id: string;
        accessKey: string;
        status: string;
        sriResponse?: unknown;
    };
    meta: Meta;
};

export type AuthorizeInvoiceResponse = {
    data: {
        id: string;
        status: string;
        sriResponse?: unknown;
    };
    meta: Meta;
};

export type CertificateUploadResponse = {
    data: {
        id: string;
        name: string;
        expiresAt: string;
        subject: string;
    };
    meta: {
        requestId: string;
        timestamp: string;
    };
};

export type CertificateError = {
    error: {
        code: string;
        message: string;
    };
};

export type CertificateListResponse = {
    data: Array<Certificate>;
    meta: {
        requestId: string;
        timestamp: string;
    };
};

export type Certificate = {
    id: string;
    name: string;
    status: string;
    environment: string;
    expiresAt: string;
    createdAt: string;
};

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetApiInfoResponses = {
    /**
     * API is healthy
     */
    200: HealthResponse;
};

export type GetApiInfoResponse = GetApiInfoResponses[keyof GetApiInfoResponses];

export type GetDetailedHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/health';
};

export type GetDetailedHealthErrors = {
    /**
     * One or more systems degraded
     */
    503: HealthResponse;
};

export type GetDetailedHealthError = GetDetailedHealthErrors[keyof GetDetailedHealthErrors];

export type GetDetailedHealthResponses = {
    /**
     * All systems healthy
     */
    200: HealthResponse;
};

export type GetDetailedHealthResponse = GetDetailedHealthResponses[keyof GetDetailedHealthResponses];

export type GetApiInfo2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health';
};

export type GetApiInfo2Responses = {
    /**
     * API is healthy
     */
    200: HealthResponse;
};

export type GetApiInfo2Response = GetApiInfo2Responses[keyof GetApiInfo2Responses];

export type GetDetailedHealth2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health/health';
};

export type GetDetailedHealth2Errors = {
    /**
     * One or more systems degraded
     */
    503: HealthResponse;
};

export type GetDetailedHealth2Error = GetDetailedHealth2Errors[keyof GetDetailedHealth2Errors];

export type GetDetailedHealth2Responses = {
    /**
     * All systems healthy
     */
    200: HealthResponse;
};

export type GetDetailedHealth2Response = GetDetailedHealth2Responses[keyof GetDetailedHealth2Responses];

export type ListInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'draft' | 'pending' | 'sent' | 'authorized' | 'rejected' | 'voided';
        page?: number;
        limit?: number;
    };
    url: '/v1/invoices';
};

export type ListInvoicesResponses = {
    /**
     * List of invoices
     */
    200: InvoiceListResponse;
};

export type ListInvoicesResponse = ListInvoicesResponses[keyof ListInvoicesResponses];

export type CreateInvoiceData = {
    body?: CreateInvoiceRequest;
    path?: never;
    query?: never;
    url: '/v1/invoices';
};

export type CreateInvoiceErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type CreateInvoiceError = CreateInvoiceErrors[keyof CreateInvoiceErrors];

export type CreateInvoiceResponses = {
    /**
     * Invoice created successfully
     */
    201: CreateInvoiceResponse;
};

export type CreateInvoiceResponse2 = CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type VoidInvoiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}';
};

export type VoidInvoiceErrors = {
    /**
     * Not implemented
     */
    501: Error;
};

export type VoidInvoiceError = VoidInvoiceErrors[keyof VoidInvoiceErrors];

export type GetInvoiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}';
};

export type GetInvoiceErrors = {
    /**
     * Invoice not found
     */
    404: Error;
};

export type GetInvoiceError = GetInvoiceErrors[keyof GetInvoiceErrors];

export type GetInvoiceResponses = {
    /**
     * Invoice details
     */
    200: InvoiceDetailResponse;
};

export type GetInvoiceResponse = GetInvoiceResponses[keyof GetInvoiceResponses];

export type SendInvoiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}/send';
};

export type SendInvoiceErrors = {
    /**
     * Invalid invoice status or missing certificate
     */
    400: Error;
    /**
     * Invoice not found
     */
    404: Error;
};

export type SendInvoiceError = SendInvoiceErrors[keyof SendInvoiceErrors];

export type SendInvoiceResponses = {
    /**
     * Invoice sent successfully
     */
    200: SendInvoiceResponse;
};

export type SendInvoiceResponse2 = SendInvoiceResponses[keyof SendInvoiceResponses];

export type AuthorizeInvoiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}/authorize';
};

export type AuthorizeInvoiceErrors = {
    /**
     * Invoice has no access key
     */
    400: Error;
    /**
     * Invoice not found
     */
    404: Error;
};

export type AuthorizeInvoiceError = AuthorizeInvoiceErrors[keyof AuthorizeInvoiceErrors];

export type AuthorizeInvoiceResponses = {
    /**
     * Authorization result
     */
    200: AuthorizeInvoiceResponse;
};

export type AuthorizeInvoiceResponse2 = AuthorizeInvoiceResponses[keyof AuthorizeInvoiceResponses];

export type GetInvoicePdfData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}/pdf';
};

export type GetInvoicePdfErrors = {
    /**
     * Invoice not found
     */
    404: Error;
};

export type GetInvoicePdfError = GetInvoicePdfErrors[keyof GetInvoicePdfErrors];

export type GetInvoicePdfResponses = {
    /**
     * PDF file
     */
    200: unknown;
};

export type GetInvoiceXmlData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/invoices/{id}/xml';
};

export type GetInvoiceXmlErrors = {
    /**
     * Invoice or XML not found
     */
    404: Error;
};

export type GetInvoiceXmlError = GetInvoiceXmlErrors[keyof GetInvoiceXmlErrors];

export type GetInvoiceXmlResponses = {
    /**
     * XML file
     */
    200: unknown;
};

export type UploadCertificateData = {
    body?: {
        /**
         * P12 certificate file
         */
        file?: Blob | File;
        password: string;
        alias?: string;
    };
    path?: never;
    query?: never;
    url: '/v1/certificates/upload';
};

export type UploadCertificateErrors = {
    /**
     * Invalid file or certificate
     */
    400: CertificateError;
    /**
     * Invalid password
     */
    401: CertificateError;
};

export type UploadCertificateError = UploadCertificateErrors[keyof UploadCertificateErrors];

export type UploadCertificateResponses = {
    /**
     * Certificate uploaded successfully
     */
    201: CertificateUploadResponse;
};

export type UploadCertificateResponse = UploadCertificateResponses[keyof UploadCertificateResponses];

export type ListCertificatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/certificates';
};

export type ListCertificatesResponses = {
    /**
     * List of certificates
     */
    200: CertificateListResponse;
};

export type ListCertificatesResponse = ListCertificatesResponses[keyof ListCertificatesResponses];
